### ISSUE TITLE
track: Lexer tracking issue

### ISSUE THREAD

**Issue by ThePuzzlemaker** [calypso-lang/calypso#17]
This is a tracking issue for the lexer, contained within `calypso_parsing::lexer`. This is marked as blocking as it is impossible for Calypso to function without the lexer fully functioning.

# Updates

- 12/12/20: The lexer has been split into multiple files (and `clippy::pedantic` has been enabled for `calypso_parsing`) as of d9d988c.
- 3/24/21: The lexer is mostly done, but is purposefully incomplete. Literals are pretty much done though.
- 8/5/21: Rewrote lexer using logos. Less expressive error handling, but still pretty effective.

# Checklist

- [x] Lexer debug interface (`int lex`)
- [x] Basic tokens (e.g. `<`, `+=`, ...) -- partially done, but mostly disabled for productivity:tm:
- [x] Keywords
- [x] Identifiers
- [x] Literals
  - [x] Character literals
  - [x] String literals
  - [x] Number literals
    - [x] Signed integer literals
    - [x] Unsigned integer literals
    - [x] Float literals
- [x] Testing
  - [x] Diagnostics
  - [x] Correct operation
