### ISSUE TITLE
track: Parser tracking issue

### ISSUE THREAD

**Issue by ThePuzzlemaker** [calypso-lang/calypso#30]
This is a tracking issue for the parser, contained within `calypso_parsing::parser`. This is marked as blocking as it is impossible for Calypso to function without the parser fully functioning.

# Updates

# Checklist

- [ ] Expressions
  - [x] Basic arithmetic and comparisons
  - [ ] Functions, pipelines, etc.
  - [ ] Blocks
  - [ ] Looping constructs
  - [ ] Pattern matching
- [ ] Items
  - [ ] Functions
  - [ ] Structs, enums, type aliases

This is probably not a complete list as I haven't finished the redesign quite yet.
